kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-stack
  namespace: llama
  labels:
    app: redis-stack
    app.kubernetes.io/component: redis-stack
    app.kubernetes.io/instance: redis-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: redis-stack
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: redis-stack
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
      - name: data-volume
        emptyDir:
          sizeLimit: 500Mi
      containers:
        - name: redis-stack
          volumeMounts:
          - mountPath: /data
            name: data-volume
          image: >-
            redis/redis-stack@sha256:028c19b1a8bc6bc4947a52dc8b221fcf5df2631787d7b7e8aabf266cc4760781
          ports:
            - containerPort: 6379
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
